@startuml

state idle
idle : state 0
idle : front cam. off
idle : rear cam. off

state frontTimer
frontTimer : state 1
frontTimer : front cam. on
frontTimer : rear cam. off
frontTimer : timer

state rearTimer
rearTimer : state 2
rearTimer : front cam. off
rearTimer : rear cam. on
rearTimer : timer

state reversing {
    state reversingRearOn
    reversingRearOn : state 3
    reversingRearOn : front cam. off
    reversingRearOn : rear cam. on

    state reveringFrontTimer
    reveringFrontTimer : state 4
    reveringFrontTimer : front cam. on
    reveringFrontTimer : rear cam. off
    reveringFrontTimer : timer

    [*] --> reversingRearOn
    reversingRearOn -> reveringFrontTimer : button pressed
    reveringFrontTimer -> reversingRearOn : timer timeout
    reveringFrontTimer -> reversingRearOn : button pressed
    reversingRearOn --> [*]
}

[*] --> frontTimer

frontTimer --> idle : timer timeout
frontTimer -left-> rearTimer : button pressed
frontTimer -> reversing : reverse gear set

idle -> idle : waiting for input
idle --> reversing : reverse gear set
idle --> frontTimer : button pressed

rearTimer --> idle : timer timeout
rearTimer --> idle : button pressed
rearTimer --> reversing : reverse gear set


reversing -> frontTimer : reverse gear unset
@enduml